### ISSUE TITLE
grafana-agent helm chart should include CustomResourceDefinitions for PodMonitor, ServiceMonitor, Probe

### ISSUE THREAD

**Issue by Skaronator** [grafana/alloy#221] opened 2024-03-12 07:45 UTC
### What's wrong?

I'm currently setting up Grafana Agent in a new cluster and I noticed that the flow mode is the new preferred way how to do that and the Grafana Operator is no longer recommended. After installing the helm-chart I noticed that the ServiceMonitor, PodMonitor, Probe and PrometheusRule CRD were missing. 

How am I supposed to use the [prometheus.operator.servicemonitors](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.operator.servicemonitors/),  [prometheus.operator.podmonitors](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.operator.podmonitors/) and [mimir.rules.kubernetes](https://grafana.com/docs/agent/latest/flow/reference/components/mimir.rules.kubernetes/) when the Custom Resource Definitions aren't provided?

### Steps to reproduce

Looking into the Helm-Chart it only provides CRD for Grafana CRD: https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent/charts/crds/crds

Comparing this to the Grafana Agent Operator Helm-Chart which provides all CoreOS CRD: https://github.com/grafana/helm-charts/tree/main/charts/agent-operator/crds

### Software version

Grafana Agent Helm Chart 0.36.0

**Comment by rfratto** [comment] 2024-06-14 16:39
Hi, this is a duplicate of #173; going to close it in favor of the existing proposal.

**Closed by rfratto** 2024-06-14 16:39 UTC
Labels: bug
