### ISSUE TITLE
add lifecycle on pod_template

### ISSUE THREAD

**Issue by jianpingzhangBill** [grafana/alloy#1673] opened 2024-09-12 08:05 UTC
### Request

We running alloy in daemonset to collect pod logs. 
We use AWS spot node, it often was  removed. But the alloy pods recycled faster then other pods, it will cause some log didn't send to loki.

Can you help add `lifecycle` and `terminationGracePeriodSeconds` to pod_template?
```
lifecycle:
  preStop:
    exec:
      command: ["sleep", "30"]
```

### Use case

Can you help add `lifecycle` and `terminationGracePeriodSeconds` to pod_template?
```
terminationGracePeriodSeconds: 60
lifecycle:
  preStop:
    exec:
      command: ["sleep", "30"]
```

**Comment by etiennep** [comment] 2024-09-17 21:33
This is a duplicate of #1140

**Comment by etiennep** [comment] 2024-09-26 22:00
Here's a PR that adds these features: https://github.com/grafana/alloy/pull/1774

**Closed** 2024-10-02 00:31 UTC
Labels: enhancement
