### ISSUE TITLE
Pyroscope forwarding through Alloy

### ISSUE THREAD

**Issue by jalaziz** [grafana/alloy#984] opened 2024-06-05 00:49 UTC
### Request

Currently, Alloy only supports forwarding pyroscope profiles scraped from pprof endpoints, eBPF, and Java. It would be great if Allow could act as a general Pyroscope proxy, exposing an HTTP endpoint sink that can accept submitted profiles and forward them to a deployed Pryroscope instance or Grafana Cloud.

### Use case

The pyroscope SDKs offer support for many languages. However, using the SDK to push profiles to Grafana Cloud in certain environments can be problematic or difficult due to network restrictions and secrets management.

Many other solutions (Vector, Grafana Agent, etc), support models where metrics, logs, traces, etc can be pushed to a private (or even local) endpoint that then forwards to a hosted service.

Having Alloy act as a Pyroscope forwarder / proxy allows for secure and scalable deployment models where applications can push profiles to a local Alloy agent (e.g. k8s Daemonset), which then further route profiles to an Alloy agent with public internet access and Grafana Cloud credentials configured.

**Comment by ptodev** [comment] 2024-08-21 16:30
Hi @jalaziz! Thank you for raising an issue. I'm going to close this one, because it seems to be a duplicate of #270.

**Closed by ptodev** 2024-08-21 16:30 UTC
Labels: enhancement, needs-attention
