### ISSUE TITLE
Add push endpoint for jfr/pprof pyroscope/phlare protocol

### ISSUE THREAD

**Issue by tomershafir** [grafana/alloy#395] opened 2023-08-06 10:06 UTC
### Request

Add push endpoint for jfr/pprof pyroscope/phlare protocol

### Use case

Profiles are generally events and less fit the pull model like metrics (there are tradeoffs, of course). Thus, I think grafana agent should support the common case of user applying a push model with a jfr/pprof pyroscope/phlare endpoint, providing intermediate collector functions external to the data plane, with batching being a critical feature, and also filtering. I may be able to help contribute.

**Comment by ptodev** [comment] 2024-08-21 16:33
Hi @tomershafir! Thank you for raising an issue. I'm going to close this one, because it seems to be a duplicate of #270.

**Closed by ptodev** 2024-08-21 16:33 UTC
Labels: enhancement
